# Generated by Django 5.0.6 on 2024-06-12 17:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_send_datetime', models.DateTimeField()),
                ('frequency', models.CharField(choices=[('daily', 'Раз в день'), ('weekly', 'Раз в неделю'), ('monthly', 'Раз в месяц')], max_length=20)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='MailingSrv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='время начала рассылки')),
                ('next_send_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='время следующей рассылки')),
                ('finish_datetime', models.DateTimeField(verbose_name='время завершения рассылки')),
                ('status', models.CharField(choices=[('создана', 'создана'), ('запущена', 'запущена'), ('завершена', 'завершена')], default='создана', max_length=100, verbose_name='статус рассылки')),
                ('frequency', models.CharField(choices=[('один раз', 'один раз'), ('раз в день', 'раз в день'), ('раз в неделю', 'раз в неделю'), ('раз в месяц', 'раз в месяц')], max_length=50, verbose_name='периодичность рассылки')),
                ('is_activated', models.BooleanField(default=True, verbose_name='метка активности')),
            ],
            options={
                'verbose_name': 'Сервис рассылок',
                'verbose_name_plural': 'Сервисы рассылок',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='SendingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('failure', 'Не успешно')], max_length=100, verbose_name='статус')),
                ('server_response', models.TextField(blank=True, null=True, verbose_name='ответ сервера')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='время отправки')),
            ],
            options={
                'verbose_name': 'Попытка отправки',
                'verbose_name_plural': 'Попытки отправки',
            },
        ),
    ]
